pets/api/urls.py
from django.conf.urls import url

from api import views

urlpatterns = [
    url(r'^pets/$', views.ListPets.as_view(), name='list_pets'),
    url(r'^cities/$', views.CityList.as_view(), name='city-list'),
    url(r'^states/$', views.StateList.as_view(), name='state-list'),
    url(r'^users/$', views.UserList.as_view(), name='user-list'),
]

pets/apps/adopcion/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView
from django.contrib.auth.views import LogoutView

from . import views

urlpatterns = [    
    url(r'^(?P<pk>[-\w]*)/$', views.post_new, name='create'),
    url(r'^logros$', views.logros, name='logros'),
    url(r'^tenure_create/(?P<pk>[-\w]*)/$', views.responsible_tenure, name='tenure_create'),
    url(r'^contratos/(?P<id>[-\w]*)/foto/$', views.upload_image, name='upload_image'),
    url(r'^contratos/(?P<m>(\d+))/(?P<u>(\d+))/reference/$', views.reference_add, name='reference_add'),
    #url(r'^check/(?P<e>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})$', views.checkusername, name='check'),
    url(r'^check/(?P<string>.*)$', views.checkusername, name='check'),
    url(r'^evidence/(?P<m>(\d+))/(?P<u>(\d+))/$', views.AdjuntarSeguimiento, name='user_evidence'),
    url(r'^sendnoti_evidence/(?P<relacion>(\d+))/(?P<t>(\d+))/$', views.notify_evidence, name='sendnoti_evidence'),

    #url(r'^$', views.post_new, name='create'),
]

pets/apps/meupet/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from . import views

urlpatterns = [
    # I'll keep this here for compatibility with links shared
    # on Facebook.
    url(r'^new/$', RedirectView.as_view(pattern_name='meupet:register', permanent=True)),
    url(r'^search/$', RedirectView.as_view(pattern_name='meupet:search', permanent=True)),

    url(r'^$', views.PetIndexView.as_view(), name='index'),
    url(r'^novo/$', views.RegisterPetView.as_view(), name='register'),
    url(r'^busca/$', views.SearchView.as_view(), name='search'),
    url(r'^atualizar-cadastro/(?P<request_key>\w+)/$', views.update_register, name='update_register'),
    url(r'^pet/(?P<slug>[-\w]*)/foto/$', views.upload_image, name='upload_image'),
    url(r'^(?P<slug>[-\w]*)/editar/$', views.EditPetView.as_view(), name='edit'),
    url(r'^(?P<slug>[-\w]*)/poster/$', views.poster, name='poster'),
    url(r'^(?P<slug>[-\w]*)/editar/situacao/$', views.change_status, name='change_status'),
    url(r'^(?P<slug>[-\w]*)/deletar/$', views.delete_pet, name='delete_pet'),
    url(r'^(?P<slug>[-\w]*)/registrado/$', views.registered, name='registered'),
    url(r'^(?P<pk_or_slug>[-\w]*)/$', views.pet_detail_view, name='detail'),
    url(r'^(?P<pk>[0-9]+)/$', views.pet_detail_view, name='detail_by_pk'),
    url(r'^(?P<group>[-\w]*)/(?P<kind>[-\w]*)/$', views.pet_list, name='pet_list'),
    #vistas agregadas
    url(r'^(?P<pk_or_slug>[-\w]*)/historia$', views.pet_tracing_view, name='tracing'),
]

pets/apps/users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LogoutView

from django.contrib.auth.decorators import login_required

from . import views, admin_views

from apps.users.admin import AdminFundacion
from django.contrib import admin
#admin.autodiscover()

from .admin_views import (
    OwnerProfileList,
    OwnerProfileDetail,
    OwnerProfileCreation,
    OwnerProfileUpdate,
    OwnerProfileDelete,

    PostulanteList,
    AdoptanteList,
    SeguimientoList,

    ContratoList,
    IniciarContrato,
    GenerarContrato,

    AdminIndex
)

urlpatterns = [
    
    #url(r'^$fundacion', views.CreateFundacionView.as_view(), name='createFundacion'), 
    #url(r'^blabla$', admin_views.report),
    #url(r'^fundacion-admin/$', AdminFundacion.urls),
    url(r'^$', views.SelectCreate, name='createSelect'), 
    
    url(r'^normal$', views.CreateUserView.as_view(), name='create'),
    #url(r'^fundacion$', views.CreateFundacionView, name='createFundacion'),  
    url(r'^fundacion$', views.CreateFView.as_view(), name='createFundacion'), 
    url(r'^profile/(?P<pk>[0-9]+)/$', views.ProfileDetailView.as_view(), name='user_profile'),
    url(r'^profile/$', views.UserProfileView.as_view(), name='profile'),
    url(r'^profile/edit/$', views.EditUserProfileView.as_view(), name='edit'), 
    url(r'^profile/edit_fundacion/$', views.EditFundacionProfileView.as_view(), name='edit_fundacion'),
    url(r'^login/$', views.UserLogin.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^confirm/$', views.confirm_information, name='confirm_information'),
    url(r'^recover/$', views.RecoverView.as_view(), name='recover_password'),
    url(r'^recover/reset/done/$', views.RecoverResetDoneView.as_view(), name='recover_password_done'),
    url(r'^recover/reset/(?P<token>.+)/$', views.RecoverResetView.as_view(), name='recover_password_reset'),
    url(r'^recover/(?P<signature>.+)/$', views.RecoverDoneView.as_view(), name='recover_password_sent'),

    url(r'^DoneUser$', views.UserDoneCreate, name='userdone'),
    url(r'^DoneFundacion$', views.FundacionDoneCreate, name='fundone'),

    #Urls para el crud
    url(r'^administrador/$', login_required(AdminIndex), name='f_index'),
    
     url(r'^administrador/list$', login_required(OwnerProfileList.as_view()), name='f_list'),
    url(r'^administrador/(?P<pk>\d+)$', login_required(OwnerProfileDetail.as_view()), name='f_detail'),
    url(r'^administrador/nuevo$', login_required(OwnerProfileCreation.as_view()), name='f_new'),
    url(r'^administrador/editar/(?P<pk>\d+)$', login_required(OwnerProfileUpdate.as_view()), name='f_edit'),
    url(r'^administrador/borrar/(?P<pk>\d+)$', login_required(OwnerProfileDelete.as_view()), name='f_delete'),

    url(r'^administrador/postulantes$', login_required(PostulanteList.as_view()), name='r_list'),
    url(r'^administrador/adoptantes$', login_required(AdoptanteList.as_view()), name='a_list'),
    url(r'^administrador/seguimiento$', login_required(SeguimientoList.as_view()), name='s_list'),

    url(r'^administrador/contratos/list$', login_required(ContratoList.as_view()), name='c_list'),

    url(r'^administrador/contratos/(?P<m>(\d+))/(?P<u>(\d+))/$', login_required(IniciarContrato), name='c_new'),
    url(r'^administrador/contratos/generar/(?P<r>(\d+))$', login_required(GenerarContrato), name='c_generar'),
    #url(r'^contrato/(?P<pk>\d+)$', ContratoCreation.as_view(), name='c_new'),
]

pets/pets/urls.py
from django.conf import settings
from django.conf.urls import include, url, static
from django.contrib import admin
from django.views.static import serve

#app_name = 'meupet'
#urlpatterns = [
    #url(r'^pets/', include('meupet.urls', namespace='meupet')),
#    url(r'^pets/', include(('meupet.urls', 'meupet'), namespace='meupet')),
    #path(r'^pets/', include('meupet.urls', namespace='meupet')),
#    url(r'^social/', include('social_django.urls', namespace='social')),
#    url(r'^user/', include('users.urls', namespace='users')),
#    url(r'^api/', include('api.urls', namespace='api')),
#    url(r'^admin/', include(admin.site.urls)),
#    url(r'^', include('common.urls', namespace='common')),
#
#]
admin.autodiscover()
urlpatterns = [
    url(r'^pets/', include(('apps.meupet.urls', 'meupet'), namespace='meupet')),
    url(r'^social/', include(('social_django.urls', 'social'), namespace='social')),
    url(r'^user/', include(('apps.users.urls', 'users'), namespace='users')),
    url(r'^api/', include(('api.urls', 'api'), namespace='api')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include(('apps.common.urls', 'common'), namespace='common')),
    url(r'^adopcion/', include(('apps.adopcion.urls', 'adopcion'), namespace='adopcion')),
    url(r'^gmaps/', include(('apps.gmaps.urls', 'gmaps'), namespace="gmaps")),
    
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]



if settings.DEBUG:
    urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pets/apps/adopcion/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
import datetime
from django.utils.timezone import now

class Contratos(models.Model):  
    BASE = '1'
    PERSONALIZADO = '2'
    TIPO = (
        (BASE, _('Base')),
        (PERSONALIZADO, _('Personalizado')),
    )  
    ADOPCIÓN = '1'
    HOGAR = '2'
    APADRINAMIENTO = '2'
    OBJETO = (
        (ADOPCIÓN, _('Adopción')),
        (HOGAR, _('Hogar de paso')),
        (APADRINAMIENTO, _('Apadrinamiento')),
    )  
    nombre = models.CharField(max_length=250)
    objeto = models.CharField(max_length=1, choices=OBJETO)   
    fecha_creacion = models.DateTimeField()
    descripcion = models.TextField()
    observaciones = models.TextField(blank=True, null=True)
    tipo = models.CharField(max_length=1, choices=TIPO)
    contrato_base = models.ForeignKey('self', blank=True, null=True, on_delete=models.PROTECT)
    fundacion = models.ForeignKey('users.Fundacion', models.DO_NOTHING, blank=True, null=True)

    def __str__(self):
        return self.nombre

class Clausulas(models.Model):
    BASE = '1'
    PERSONALIZADO = '2'
    TIPO = (
        (BASE, _('Base')),
        (PERSONALIZADO, _('Personalizado')),
    )  
    nombre = models.CharField(max_length=250)
    fecha_creacion = models.DateTimeField()
    descripcion = models.TextField()
    observaciones = models.TextField(blank=True, null=True)
    tipo = models.CharField(max_length=1, choices=TIPO)
    contrato = models.ForeignKey('Contratos', models.DO_NOTHING)

    def __str__(self):
        return self.nombre

class TipoRelacion(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField(max_length=500)
    observaciones = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.nombre

class Relacion(models.Model):
    usuario = models.ForeignKey('users.OwnerProfile', on_delete=models.CASCADE, db_column='usuario')
    mascota = models.ForeignKey('meupet.Pet',on_delete=models.CASCADE, db_column='mascota')
    fecha = models.DateTimeField()
    tipo_relacion = models.ForeignKey('TipoRelacion',  on_delete=models.CASCADE, db_column='tipo_relacion')
 
    class Meta:
        unique_together = ('usuario', 'mascota')

    def cambiar_adopcion(self):
        tipor = TipoRelacion.objects.get(nombre__contains='Adopc')
        self.tipo_relacion = tipor
        self.save()

    def get_fecha_actual(self):
        #formatedDate = timezone.localtime(timezone.now()).date().strftime("%Y-%B-%d")
        #return str(formatedDate)
        return timezone.now()

    def get_dia_actual(self):
        formatedDate = timezone.localtime(timezone.now()).date().strftime("%d")
        return int(str(formatedDate))

    def __str__(self):
        return self.tipo_relacion.nombre+str(' - ')+self.usuario.first_name+str(' & ')+self.mascota.name

class Seguimiento(models.Model):
    EVIDENCIA = '1'
    VISITA = '2'
    CONTRATO = '3'
    TIPO = (
        (EVIDENCIA, _('Evidencia')),
        (VISITA, _('Visita')),
        (CONTRATO, _('Contrato')),
    ) 
    CELEBRACION = '1'
    APROBACIÓN = '2'
    ANULACIÓN = '3'
    PENDIENTE = '4'
    ANOMALIAS = '5'
    ESTADO = (
        (CELEBRACION, _('Celebración')),
        (APROBACIÓN, _('Aprobación')),
        (ANULACIÓN, _('Anulación')),
        (PENDIENTE, _('Pendiente')),
        (ANOMALIAS, _('Anomalias')),
    ) 
    tipo = models.CharField(max_length=1, choices=TIPO)
    estado = models.CharField(max_length=1, choices=ESTADO)
    fecha = models.DateTimeField(default=now)
    titulo = models.CharField(max_length=100, blank=True, null=True)
    observaciones = models.TextField(max_length=2000, blank=True, null=True)
    notificaciones = models.IntegerField(default=0)
    anterior = models.OneToOneField('self', blank=True, null=True, on_delete=models.PROTECT)
    relacion = models.ForeignKey('Relacion', models.DO_NOTHING)

    def __str__(self):
        formatedDate = self.fecha.strftime("%Y-%B-%d %H:%M")
        return str(formatedDate)+str("-")+str(dict(self.TIPO).get(self.tipo))+str("|")+str(dict(self.ESTADO).get(self.estado))+str(self.relacion)

    def get_days_due(self):
        adjunto = Adjuntos_Seguimiento.objects.filter(seguimiento=self.id)
        dias = timezone.now() - self.fecha
        return str(dias.days)

    def notify_add(self):
        self.notificaciones = self.notificaciones + 1
        self.save()

    get_days_due.short_description = 'Dias debidos'

class Adjuntos_Seguimiento(models.Model):
    seguimiento = models.ForeignKey(Seguimiento, models.DO_NOTHING)
    adjunto = models.ImageField(upload_to='adopcion_seguimiento',
                                        help_text=_('Maximo tamaño de imagen 8mb'))

    def __str__(self):
        return str("Adj. Id:")+str(self.id)+str("-")+str(self.seguimiento)

pets/apps/adopcion/templates/adopcion/adopcion_done.html
{% extends 'adminlte/base.html' %}
{% load i18n static %}
{% block content %}
  <div class="row">
    <div class="col-md-9">

      <h2>{{ relacion.usuario.nombre_completo }} Ha adoptado a {{ relacion.mascota.name }}!</h2>

      <p>Esta informacion sera compartida automaticamente en <a href="https://www.facebook.com/fbfundacion">Facebook</a>
        y tambien en <a href="https://twitter.com/twfundacion">Twitter</a> de la fundación {{ relacion.usuario.fundacion.nombre_corto }} ! :)</p>

      <p>Para ver los detalles de este gran amigo <a href="{% url 'meupet:detail' pet_slug %}">aqui</a>.</p>

      <p>
        Sigue descrubriendo nuevos amigos en  <a href="{% url 'meupet:index'  %}">aqui</a>.</p>.</p>

      <p>Puedes compartir este sitio en las redes sociales</p>

      <ul class="list-unstyled list-inline">
        <li>
          <a href="{{ facebook_url }}" target="#" rel="noreferrer noopener">
            <img src="{% static 'img/facebook.png' %}" alt="Facebook"/>
          </a>
        </li>
        <li>|</li>
        <li>
          <a href="{{ twitter_url }}" target="_blank" rel="noreferrer noopener">
            <img src="{% static 'img/twitter.png' %}" alt="Twitter"/>
          </a>
        </li>
      </ul>

      <p>Gracias por tu apoyo! <i class="c-red fa fa-heart"></i></p>
    </div>
  </div>
{% endblock %}

pets/apps/adopcion/templates/adopcion/adopcion_index.html
{% extends 'adminlte/base.html' %}

pets/apps/adopcion/templates/adopcion/cargar_evidencia.html
{% extends '_layouts/base.html' %}
{% load i18n static thumbnail %}

{% block title %}{% trans 'Historias junto a ' %}{{ relacion.mascota.name }}{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-9">
      {% if flag == 1 %}
      <!--<div class="alert alert-success">{{ user_name }} anteriormente te habias postulado para una mascota, tus datos han sido actualizados...!</div>-->
      {% endif %}
      <h2>{{ user_name }} Cuentanos como te la estas pasando al lado de {{ relacion.mascota.name }}!</h2>

       <p>A continuación proporciona cualquier contenido que quieras añadir a la historia entre {{ relacion.mascota.name }} y tú.</p>

       <form class="form-horizontal" method="POST" enctype="multipart/form-data"
       action="{% url 'adopcion:upload_image' relacion.id %}">
       {% csrf_token %}
       <input name="pet_id" value="{{ relacion.mascota.id }}" type="hidden">

       <div class="form-group">
        <div class="col-md-6">
          <!--<label for="another_picture" class="control-label">{% trans 'Agregar foto' %}</label>-->
          <input type="file" id="another_picture" name="another_picture">
        </div>

        <div class="col-md-6">
          <input type="submit" name="submit" class="btn btn-primary" value="{% trans 'Subir Imagen' %}">
        </div>
        </div>
        </form>

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-primary" type="submit" value="Enviar evidencia" />
        </form>

        {% if seguimiento.adjuntos_seguimiento_set.all %}
        <div class="col-md-12">
          <h3>{% trans 'Mira tu Story Line' %}</h3>

          <div class="row">
            {% for adjuntos_seguimiento in seguimiento.adjuntos_seguimiento_set.all %}
            <div class="col-md-3">
              <a href="{{ adjuntos_seguimiento.adjunto.url }}" data-lightbox="{{ adjuntos_seguimiento }}" data-title="{{ relacion.mascota }}">
                <img class="img-thumbnail" src="{{ adjuntos_seguimiento.adjunto|thumbnail_url:'seguimiento_thumb' }}"
                alt="{{ relacion }}"/>
              </a>
            </div>
            {% if forloop.counter|divisibleby:4 %}
          </div>
          <div class="row">
            {% endif %}
            {% endfor %}
          </div>
        </div>
        {% endif %}
      <br>
      <ul class="list-unstyled list-inline">
        <li>
          <a href="{{ facebook_url }}" target="#" rel="noreferrer noopener">
            <img src="{% static 'img/facebook.png' %}" alt="Facebook"/>
          </a>
        </li>
        <li>|</li>
        <li>
          <a href="{{ twitter_url }}" target="_blank" rel="noreferrer noopener">
            <img src="{% static 'img/twitter.png' %}" alt="Twitter"/>
          </a>
        </li>
      </ul>

      <p>Gracias por tu apoyo! <i class="c-red fa fa-heart"></i></p>
    </div>
  </div>
{% endblock %}

pets/apps/adopcion/templates/adopcion/contratos_form.html
{% extends 'adminlte/base.html' %}

{% block title %}Formulario{% endblock %}
{% block content %}
    <form method="post">
	    {% csrf_token %}
	    {{ form.as_p }}
	    <input class="btn btn-primary" type="submit" value="Guardar Cambios" />
	</form>
{% endblock %}

pets/apps/adopcion/templates/adopcion/contratos_list.html
{% extends 'adminlte/base.html' %}

{% block logo %}
    <div class="login-logo">
    <a href="{% block logo_href %}/{% endblock %}">
        {% block logo_text %}<b>Dale</b>La Pata{% endblock %}</a>
    </div>
{% endblock %}
{% block scripts %}

{% endblock %}
{% block content %}
    <div class="table-responsive">          
      <table id="myTable" class="table">
        <thead>
          <tr class="clickable-row">
            <th>id</th>
            <th>nombre</th>
            <th>descripcion</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          {% for contratos_fundacion in object_list %}
          <tr>
            <td>{{ contratos_fundacion.id}} </td>
            <td>{{ contratos_fundacion.descripcion_base }}</td>
            <td>{{ contratos_fundacion.fecha }}</td>
            <td><a href="">Ver</a> | <a href="">Contrato Adopción</a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
{% endblock %}

pets/apps/adopcion/templates/adopcion/done.html
{% extends '_layouts/base.html' %}
{% load i18n static thumbnail %}

{% block title %}{% trans 'Postulaciòn exitosa' %}{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-9">
      {% if flag == 1 %}
        <div class="alert alert-success">{{ user_name }} anteriormente te habias postulado para una mascota, tus datos han sido actualizados...!</div>
      {% endif %}
      <h2>{{ user_name }} estás a un paso de chocar la pata con {{ pet.name }}!</h2>

       <p>El registro de tu postulación fue enviado a la fundacion {{ pet.fundacion.nombre_corto }}, los cuales te contactaran para completar el
       proceso de adopcíon, puedes contactarte con ellos para agilizar el proceso</p>

      <h3>Datos fundación</h3>
      {% if pet.fundacion.logo %}
      <a href="{{ pet.fundacion.logo.url }}" data-lightbox="{{ pet.fundacion.nombre_corto }}" data-title="{{ pet.fundacion }}">
      <img class="img-thumbnail" src="{{ pet.fundacion.logo|thumbnail_url:'fundacion_thumb' }}"
             alt="{{ pet.fundacion }}"/>
      </a>
      {% endif %}

      <p>{{ pet.fundacion.tipo_identificacion }} - {{ pet.fundacion.num_identificacion }}</p>
      <p>Nombre: {{ pet.fundacion.nombre_corto }}</p>
      <p>email: {{ pet.fundacion.email }}</p>
      <p>telefono: {{ pet.fundacion.telefono }}</p>

      <p>Esta informacion sera compartida automaticamente en <a href="https://www.facebook.com/fbfundacion">Facebook</a>
        y tambien en <a href="https://twitter.com/twfundacion">Twitter</a> de la fundación [] ! :)</p>

      <p>Para ver los detalles de este gran amigo <a href="{% url 'meupet:detail' pet.slug %}">aqui</a>.</p>

      <p>
        Sigue descrubriendo nuevos amigos en  <a href="{% url 'meupet:index'  %}">aqui</a>.</p>.</p>

      <p>Puedes compartir este sitio en las redes sociales</p>

      <ul class="list-unstyled list-inline">
        <li>
          <a href="{{ facebook_url }}" target="#" rel="noreferrer noopener">
            <img src="{% static 'img/facebook.png' %}" alt="Facebook"/>
          </a>
        </li>
        <li>|</li>
        <li>
          <a href="{{ twitter_url }}" target="_blank" rel="noreferrer noopener">
            <img src="{% static 'img/twitter.png' %}" alt="Twitter"/>
          </a>
        </li>
      </ul>

      <p>Gracias por tu apoyo! <i class="c-red fa fa-heart"></i></p>
    </div>
  </div>
{% endblock %}

pets/apps/adopcion/templates/adopcion/index.html
{% extends '_layouts/base.html' %}
{% load i18n %}

{% block title %}{% trans 'Adopcion' %}{% endblock %}

{% block content %}
  {% include '_partials/pets_list.html' %}
{% endblock %}

pets/apps/adopcion/templates/adopcion/relacion_list.html
{% extends 'adminlte/base.html' %}

{% block logo %}
    <div class="login-logo">
    <a href="{% block logo_href %}/{% endblock %}">
        {% block logo_text %}<b>Dale</b>La Pata{% endblock %}</a>
    </div>
{% endblock %}
{% block scripts %}

{% endblock %}
{% block content %}
    <button><a href="{% url "users:f_new"%}">Agregar usuario</a></button>
    <div class="table-responsive">          
      <table id="myTable" class="table">
        <thead>
          <tr class="clickable-row">
            <th>Id. Postulante</th>
            <th>Postulante</th>
            <th>Chip Mascota</th>
            <th>Mascota</th>
            <th>Fecha</th>
            {% if object.is_superuser %}
            <th>Fundacion</th>
            {% endif %}
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          {% for relacion in object_list %}
          <tr>
            <td> {{ relacion.usuario.num_identificacion }} </td>
            <td><a href="{{ relacion.usuario.get_absolute_url }}"> {{ relacion.usuario.nombre_completo }} </a></td>
            <td>{{ relacion.mascota.chip_id }}</td>
            <td><a href="{{ relacion.mascota.get_absolute_url }}"> {{ relacion.mascota }} </a></td>
            <td>{{ relacion.fecha }}</td>
            {% if object.is_superuser %}
             <td>{{ relacion.mascota.fundacion.nombre_corto }}</td>
            {% endif %}

            {% if type == "postulante" %}
            <td><a href="{% url "users:c_new" relacion.mascota.id relacion.usuario.id  %}">Realizar contrato</a></td>
            {% endif %}
            {% if type == "adoptante" %}
            <td><a href="{% url "adopcion:sendnoti_evidence" relacion.id 0 %}">Solicitar evidencia</a></td>
            {% endif %}

          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
{% endblock %}

pets/apps/adopcion/templates/adopcion/seguimiento_list.html
{% extends 'adminlte/base.html' %}

{% block logo %}
    <div class="login-logo">
    <a href="{% block logo_href %}/{% endblock %}">
        {% block logo_text %}<b>Dale</b>La Pata{% endblock %}</a>
    </div>
{% endblock %}
{% block scripts %}

{% endblock %}
{% block content %}
    <!-- <button><a href="{% url "users:f_new"%}">Agregar usuario</a></button> -->
    <div class="table-responsive">          
      <table id="myTable" class="table">
        <thead>
          <tr class="clickable-row">
            <th>Id. Seguimiento</th>
            <th>Tipo</th>
            <th>F. Solicitud</th>
            <th>Usuario</th>
            <th>Compañero</th>
            <th>Dias ultima ev.</th>
            <th>Notificaciones</th>
            {% if object.is_superuser %}
            <th>Fundacion</th>
            {% endif %}
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          {% for seguimiento in object_list %}
          <tr>
            <td> {{ seguimiento.id }} </td>
            <td> {{ seguimiento.tipo }} </td>
            <td> {{ seguimiento.fecha }} </td>
            <td><a href="{{ seguimiento.relacion.usuario.get_absolute_url }}"> {{ seguimiento.relacion.usuario.nombre_completo }} </a></td>
            <td><a href="{{ seguimiento.relacion.mascota.get_absolute_url }}"> {{ seguimiento.relacion.mascota }} </a></td>
            <td> {{ seguimiento.get_days_due }} </td>
            <td> {{ seguimiento.notificaciones }} </td>
    
            {% if object.is_superuser %}
             <td>{{ seguimiento.relacion.mascota.fundacion.nombre_corto }}</td>
            {% endif %}

            <td>
              <a href="{% url "adopcion:sendnoti_evidence" seguimiento.relacion.id 0 %}">Evi. Usuario | </a>
              <a href="{% url "adopcion:sendnoti_evidence" seguimiento.relacion.id 1 %}">Evi. referencias</a>
            </td>

          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
{% endblock %}