pets/api/urls.py
from django.conf.urls import url

from api import views

urlpatterns = [
    url(r'^pets/$', views.ListPets.as_view(), name='list_pets'),
    url(r'^cities/$', views.CityList.as_view(), name='city-list'),
    url(r'^states/$', views.StateList.as_view(), name='state-list'),
    url(r'^users/$', views.UserList.as_view(), name='user-list'),
]

pets/apps/gmaps/urls.py
from django.conf.urls import url, include
from apps.gmaps.views import Mapa_Ubicacion, sitios, ubicacion_edit, ubicacion_delete, mapMapbox, Crear_Categoria, categoria_edit, categoria_delete

urlpatterns = [
    url(r'^mapaubicar$',Mapa_Ubicacion, name='Mapa_Ubicacion'),    
    url(r'^puntosMarcados$',sitios, name='sitios'),
    url(r'^editar/(?P<id_ubicacion>(\d+))/(?P<estado>([\w]+))/$', ubicacion_edit, name='ubicacion_edit'),
    url(r'^eliminar/(?P<id_ubicacion>\d+)/$', ubicacion_delete, name='ubicacion_delete'),
    url(r'^mapabox$',mapMapbox, name='mapMapbox'),    
    url(r'^categoria$',Crear_Categoria, name='Crear_Categoria'),
    url(r'^editarc/(?P<id_categoria>\d+)/$', categoria_edit, name='categoria_edit'),
    url(r'^eliminarc/(?P<id_categoria>\d+)/$', categoria_delete, name='categoria_delete'),
    
    
    
]

pets/pets/urls.py
from django.conf import settings
from django.conf.urls import include, url, static
from django.contrib import admin
from django.views.static import serve

#app_name = 'meupet'
#urlpatterns = [
    #url(r'^pets/', include('meupet.urls', namespace='meupet')),
#    url(r'^pets/', include(('meupet.urls', 'meupet'), namespace='meupet')),
    #path(r'^pets/', include('meupet.urls', namespace='meupet')),
#    url(r'^social/', include('social_django.urls', namespace='social')),
#    url(r'^user/', include('users.urls', namespace='users')),
#    url(r'^api/', include('api.urls', namespace='api')),
#    url(r'^admin/', include(admin.site.urls)),
#    url(r'^', include('common.urls', namespace='common')),
#
#]
admin.autodiscover()
urlpatterns = [
    url(r'^pets/', include(('apps.meupet.urls', 'meupet'), namespace='meupet')),
    url(r'^social/', include(('social_django.urls', 'social'), namespace='social')),
    url(r'^user/', include(('apps.users.urls', 'users'), namespace='users')),
    url(r'^api/', include(('api.urls', 'api'), namespace='api')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include(('apps.common.urls', 'common'), namespace='common')),
    url(r'^adopcion/', include(('apps.adopcion.urls', 'adopcion'), namespace='adopcion')),
    url(r'^gmaps/', include(('apps.gmaps.urls', 'gmaps'), namespace="gmaps")),
    
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]



if settings.DEBUG:
    urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pets/apps/gmaps/models.py
from django.db import models
#from django.contrib.auth.models import User
from apps.users.models import OwnerProfile
from django.utils.translation import ugettext_lazy as _


MARK = True
UNMARK = False
VISIT = (
    (MARK, _('Visitado')),
    (UNMARK, _('Pendiente')),
)

class Categoria(models.Model):
	nombre=models.CharField(max_length=200, null=False, blank=False)

	def __str__(self):
		return '{}'.format(self.nombre)


class Ubicacion(models.Model):
	nombre=models.CharField(max_length=200, null=False, blank=False)
	lat=models.CharField(max_length=50, null=False, blank=False)
	lng=models.CharField(max_length=50, null=False, blank=False)
	fecha=models.DateTimeField(auto_now_add=True)
	cantidad=models.IntegerField(default=0)
	categorias=models.ManyToManyField(Categoria, through='Tabcatub', through_fields=('location', 'category'), null=False, blank=False)
	estado=models.BooleanField(choices=VISIT, null=False, blank=False)
	fecha_inicial=models.CharField(max_length=50, null=True, blank=True)
	fecha_final=models.CharField(max_length=50, null=True, blank=True)
	foto = models.ImageField(upload_to='fotos', blank=True, null=True)
	user=models.ForeignKey(OwnerProfile,on_delete=True)


	
class Tabcatub(models.Model):
	category = models.ForeignKey(Categoria, on_delete=models.CASCADE)
	location = models.ForeignKey(Ubicacion, on_delete=models.CASCADE)  



pets/apps/gmaps/forms.py
from django import forms
#from django.forms import ModelForm
from apps.gmaps.models import Ubicacion, Categoria


class CategoriaForm(forms.ModelForm):

	class Meta:
		model = Categoria
		
		fields = [
			'nombre',
		]
		labels = {
			'nombre':'Nombre',
		}
		widgets = {
			'nombre':forms.TextInput(attrs={'class':'form-control', 'id':'nom'}),
		}



class GmapsForm(forms.ModelForm):

	class Meta:
		model = Ubicacion

		fields = [
			'nombre',
			'lat',
			'lng',
			'cantidad',
			'categorias',
			'estado',
			'fecha_inicial',
			'fecha_final',
			'foto',
			'user',
		]

		labels = {
			'nombre':'Nombre',
			'lat':'Latitud',
			'lng':'Longitud',			
			'cantidad':'Cantidad',
			'categorias':'Categoria',
			'estado':'Estado',
			'fecha_inicial':'Fecha Inicial',
			'fecha_final':'Fecha final',
			'foto':'Foto',
			'user':'Usuario',
		}
	
		widgets = {			
			'nombre':forms.TextInput(attrs={'class':'form-control'}),	
			'lat':forms.HiddenInput(),
			'lng':forms.HiddenInput(),		
			'cantidad':forms.NumberInput(attrs={'class':'form-control'}),
			'categorias':forms.CheckboxSelectMultiple(attrs={'class':'nomcats'}),
			'estado':forms.Select(attrs={'class':'form-control','id':'estadio'}),		
			'fecha_inicial':forms.TextInput(attrs={'class':'form-control','id':'proxv','placeholder':'Fecha inicial'}),
			'fecha_final':forms.TextInput(attrs={'class':'form-control','id':'fecf','placeholder':'Fecha final'}),
			'foto':forms.ClearableFileInput(attrs={'class':'form-control','id':'fot','placeholder':'Ingresa imagen visita'}),
			'user':forms.Select(attrs={'class':'form-control'}),		
		}




pets/apps/gmaps/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from apps.gmaps.forms import GmapsForm, CategoriaForm
from apps.gmaps.models import Ubicacion, Categoria, Tabcatub
from django.core import serializers
from django.core.paginator import Paginator
from django.template import RequestContext
import json


def sitios(request):
	return render(request,'gmaps/mapaPuntos.html',  {
		'puntos':serializers.serialize('json', Ubicacion.objects.all()), 
		'categs':serializers.serialize('json', Categoria.objects.all()),
		'catubs':serializers.serialize('json', Tabcatub.objects.all())
		})

def Mapa_Ubicacion(request):
	if request.method == 'POST':		
		form = GmapsForm(request.POST, request.FILES)
		if form.is_valid():
			form.save()			
		return redirect('gmaps:Mapa_Ubicacion')	
	else:
		form = GmapsForm()		
		
	return render(request,'gmaps/mapaUbicar.html',{'form':form, 'listaQ':serializers.serialize('json', Ubicacion.objects.all())})


def ubicacion_edit(request, id_ubicacion, estado):
	ubicacion=Ubicacion.objects.get(id=id_ubicacion)
	if estado=='VISITADO':
		edi='/static/img/visitado.png'
	else:
		edi='/static/img/pendiente.png'	
	if request.method=='GET':
		form=GmapsForm(instance=ubicacion);
	else:
		form = GmapsForm(request.POST, instance=ubicacion)
		if form.is_valid():
			form.save()
		return redirect('gmaps:Mapa_Ubicacion')
	return render(request,'gmaps/mapaUbicar.html',{'form':form, 'edi':edi})

def ubicacion_delete(request, id_ubicacion):
	ubicacion=Ubicacion.objects.get(id=id_ubicacion)
	if request.method=='POST':
		ubicacion.delete()
		return redirect('gmaps:Mapa_Ubicacion')
	return render(request,'gmaps/ubicacion_delete.html',{'ubicacion':ubicacion})

def mapMapbox(request):
	return render(request,'base/pruebaMapbox.html')

def normalize(s):
    replacements = (
        ("á", "a"),
        ("é", "e"),
        ("í", "i"),
        ("ó", "o"),
        ("ú", "u"),
    )
    for a, b in replacements:
        s = s.replace(a, b).replace(a.upper(), b.upper())
    return s

def check_name_cat(name_cat):
	nam_cat=normalize(name_cat)
	categorys=Categoria.objects.all()
	exists=False
	for category in categorys:
		nombrecat=normalize(category.nombre)
		if nam_cat.lower()==nombrecat.lower():
			exists=True
	return exists

def Crear_Categoria(request):
	listcats=Categoria.objects.all().order_by('id')
	if request.method == 'POST':
		formc = CategoriaForm(request.POST)		
		if formc.is_valid():
			elnombre=formc.cleaned_data['nombre'] 		
			if not check_name_cat(elnombre):
				formc.save()
		return redirect('gmaps:Crear_Categoria')	
	else:
		formc = CategoriaForm()	

	paginator=Paginator(listcats,15)
	page=request.GET.get('page')
	listcats=paginator.get_page(page)
	return render(request,'gmaps/creaCategoria.html',{'formc':formc, 'listcats':listcats, 'listaC':serializers.serialize('json', Categoria.objects.all())})


def categoria_edit(request,id_categoria):
	idcat=id_categoria
	categori=Categoria.objects.get(id=id_categoria)
	if request.method=='GET':
		formc=CategoriaForm(instance=categori);
	else:
		formc = CategoriaForm(request.POST, instance=categori)
		if formc.is_valid():
			elnombre=formc.cleaned_data['nombre'] 		
			if not check_name_cat(elnombre):
				formc.save()
		return redirect('gmaps:Crear_Categoria')
	return render(request,'gmaps/creaCategoria.html',{'formc':formc,'idcat':idcat})


def verificar_cat(id_cat):
	ubicat=Tabcatub.objects.all()
	vinculos=False
	for ub in ubicat:
		if id_cat==ub.category:
			vinculos=True
	return vinculos


def categoria_delete(request, id_categoria):
	sepuede=True
	categori=Categoria.objects.get(id=id_categoria)
	if not verificar_cat(categori):
		if request.method=='POST':
			categori.delete()
			return redirect('gmaps:Crear_Categoria')
	else:	
		sepuede=False
	return render(request,'gmaps/categoria_delete.html',{'categori':categori, 'sepuede':sepuede})	











pets/apps/gmaps/templates/gmaps/categoria_delete.html
{% extends 'adminlte/base.html' %}

{% block title %}Eliminar Categoria{% endblock %}
{% block content %}		
<form method="post">	
	{% csrf_token %}
	{% if sepuede %}
	<h3>Esta seguro que quiere eliminar la categoria {{ categori.nombre }}?</h3>
		<button class="btneliminar" type="submit">Si, Eliminar</button><br><br>
	{% else %}
		<h3>La categoria {{ categori.nombre }} tiene vinculos con sitios ya establecidos, libérela para poderla eliminar</h3>
	{% endif %}
	<a href="{% url 'gmaps:Crear_Categoria' %}">Cancelar</a>	
</form>
<img src='/static/img/eliminar.png' width="400" height="400">		
{% endblock %}

pets/apps/gmaps/templates/gmaps/creaCategoria.html
{% extends 'adminlte/base.html' %}

{% block title %}Categoria{% endblock %}
{% block content %}
<div id="datos" class="capas">	
<div id="form">
	<form method="post">
		{% csrf_token %}
		{{ formc.as_p }}		
			<button type="submit" id="consultac">Guardar Categoria</button>					
	</form>	
</div>
</div>
<div class="table-responsive">
	<table id="datoscat" class="table">
		<thead>
			<tr class="clickable-row">
				<th>#</th>
				<th>Nombre</th>
				<th>Acciones</th>
			</tr>
		</thead>
		<tbody>
		{% if listcats %}
		{% for listcat in listcats %}	
		<tr>
			<td>{{listcat.id}}</td>
			<td>{{listcat.nombre}}</td>
			<td>
				<a href="{% url 'gmaps:categoria_edit' listcat.id %}">Editar</a>
			</td>
			<td>
				<a href="{% url 'gmaps:categoria_delete' listcat.id %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}
		{% else %}
		{% if idcat %}
			<a href="{% url 'gmaps:Crear_Categoria' %}">Cancelar</a>
		{% else %}
			<h1>No hay registros de Categorias</h1>
		{% endif %}	
		{% endif %}
		</tbody>
	</table>
	{% if listcats.has_previous %}
		<a href="?page={{listcats.previous_page_number}}" style="float:left"><i class="fa fa-chevron-circle-left" aria-hidden="true"></i></a>
	{% endif %}
	{% if listcats.has_next %}
		<a href="?page={{listcats.next_page_number}}" style="float:right"><i class="fa fa-chevron-circle-right" aria-hidden="true"></i></a>
	{% endif %}
</div>
{% endblock %}

pets/apps/gmaps/templates/gmaps/mapaPuntos.html
{% extends '_layouts/base.html' %}
{% load i18n static compress %}

{% block title %}{% trans 'Presencia Unidad Movil' %}{% endblock %}

{% block content %}
 	{% csrf_token %}	
	<header>
	<input type="checkbox" id="btn-menu">
	<label for="btn-menu" class="icon-menu"></label>
<nav class="minuta">
	<ul>
		<li><a href="#">Categorias<span class="icon-down-open"></span></a>
			<ul id="checkboxes">
				<li id='primero'><input id="all" type="radio" checked='checked'>
				<label for="all">Seleccionar Todo</label>
				</li>
						
			</ul>			
		</li>
		<li><a href="#">Estado<span class="icon-down-open"></span></a>
			<ul id="estados">
				<li>
					<input type='checkbox' id='VISITADO' checked='checked'>
					<label for='VISITADO'>Visitados</label>
				</li>
				<li>
					<input type='checkbox' id='PENDIENTE' checked='checked'>
					<label for='PENDIENTE'>Pendientes</label>
				</li>
			</ul>
		</li>
	</ul>
</nav>
</header>		
<div id="titleinfo"></div>
	<section id="mapaP"></section>	
	<div style="visibility: hidden">
	 	<p id="datap">{{ puntos }}</p>
	 	<p id="datac">{{ categs }}</p>
	 	<p id="datacu">{{ catubs }}</p>
	 </div>
	 <input type="hidden" id="#datahp" value="$('#datap').html">	
	 <input type="hidden" id="#datac" value="$('#datac').html">
	 <input type="hidden" id="#datacu" value="$('#datacu').html">	 

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" id="contimg">
      <div class="modal-header" id="cabecerafoto">
        <h5 class="modal-title" id="exampleModalLabel"></h5>        
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" id="x">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="fotomodal">
        
      </div>
      <div class="modal-footer" id="footerinfo">
        
      </div>
    </div>
  </div>
</div>
 {% include '_layouts/basePuntos.html' %}

{% endblock %}

pets/apps/gmaps/templates/gmaps/mapaUbicar.html
{% extends 'adminlte/base.html' %}
{% load i18n static compress %}
{% block title %}Mapa{% endblock %}
{% block content %}

{% include '_layouts/baseMapaU.html' %}
<!--div class="container"-->
	<link href="{% static 'css/multiselect.css' %}" rel="stylesheet"/>
	<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
	<link rel="stylesheet" href="/resources/demos/style.css">

<div id="mapa" class="capas">
	{% csrf_token %}
	{% if edi %}
	<div id="icono">
		<img src='{{ edi }}' width="400" height="450">
	</div>
	{% endif %}	
</div>
<div id="datos" class="capas">	
<div id="form">	
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<label>Lugar:</label>
		{{ form.nombre }}	
		{{ form.lat }}
		{{ form.lng }}		
		<label>Cantidad:</label>
		{{ form.cantidad }}
		<nav class="minuta">
			<ul>
				<li><a href="/gmaps/categoria">Categorias<span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span></a>
					<ul id="checkboxes">
						{% for cat in form.categorias %}
							<li>
								{{cat}}								
							</li>
						{% endfor %}
					</ul>
				</li>
			</ul>
		</nav>
		<label>Estado:</label>
		{{ form.estado }}
		<label>Fecha Inicial:</label>
		{{ form.fecha_inicial }}
		<label>Fecha Final:</label>
		{{ form.fecha_final }}
		<label>Foto:</label>
		{{ form.foto }}
		<label>Usuario:</label>
		{{ form.user }}

		<button type="submit" id="consulta">Guardar Ubicación</button>		
	</form>	
	
</div>
</div>
<div id="data">
	{% csrf_token %}
	{% if edi %}
		<a href="{% url 'gmaps:Mapa_Ubicacion' %}">Cancelar</a>   
	{% endif %}
</div>
<div id="contQ">
	<div style="visibility:hidden">
		<p id="dataq">{{ listaQ }}</p>
	</div>
	 <input type="hidden" id="#datahq" value="$('#dataq').html">
 </div>
</div>

<script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>
  <script src="{% static 'js/multiselect.min.js' %}"></script>
  <script src="{% static 'js/scriptMapaU.js' %}"></script> 
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script  src = "https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"></script>
  <script src="https://unpkg.com/esri-leaflet@2.0.8"></script>
  <script src="https://unpkg.com/esri-leaflet-geocoder@2.2.4"></script>
<!--/div-->
{% endblock %}

pets/apps/gmaps/templates/gmaps/ubicacion_delete.html
{% extends 'adminlte/base.html' %}

{% block title %}Desmarcar{% endblock %}
{% block content %}	
<form method="post">
	{% csrf_token %}
	<h3>Esta seguro que quiere desmarcar el sitio de {{ ubicacion.nombre }}?</h3>
	<button class="btneliminar" type="submit">Si, Desmarcar</button><br><br>
	<a href="{% url 'gmaps:Mapa_Ubicacion' %}">Cancelar</a>	
</form>
<img src='/static/img/eliminar.png' width="400" height="400">		
{% endblock %}