pets/api/urls.py
from django.conf.urls import url

from api import views

urlpatterns = [
    url(r'^pets/$', views.ListPets.as_view(), name='list_pets'),
    url(r'^cities/$', views.CityList.as_view(), name='city-list'),
    url(r'^states/$', views.StateList.as_view(), name='state-list'),
    url(r'^users/$', views.UserList.as_view(), name='user-list'),
]

pets/apps/meupet/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from . import views

urlpatterns = [
    # I'll keep this here for compatibility with links shared
    # on Facebook.
    url(r'^new/$', RedirectView.as_view(pattern_name='meupet:register', permanent=True)),
    url(r'^search/$', RedirectView.as_view(pattern_name='meupet:search', permanent=True)),

    url(r'^$', views.PetIndexView.as_view(), name='index'),
    url(r'^novo/$', views.RegisterPetView.as_view(), name='register'),
    url(r'^busca/$', views.SearchView.as_view(), name='search'),
    url(r'^atualizar-cadastro/(?P<request_key>\w+)/$', views.update_register, name='update_register'),
    url(r'^pet/(?P<slug>[-\w]*)/foto/$', views.upload_image, name='upload_image'),
    url(r'^(?P<slug>[-\w]*)/editar/$', views.EditPetView.as_view(), name='edit'),
    url(r'^(?P<slug>[-\w]*)/poster/$', views.poster, name='poster'),
    url(r'^(?P<slug>[-\w]*)/editar/situacao/$', views.change_status, name='change_status'),
    url(r'^(?P<slug>[-\w]*)/deletar/$', views.delete_pet, name='delete_pet'),
    url(r'^(?P<slug>[-\w]*)/registrado/$', views.registered, name='registered'),
    url(r'^(?P<pk_or_slug>[-\w]*)/$', views.pet_detail_view, name='detail'),
    url(r'^(?P<pk>[0-9]+)/$', views.pet_detail_view, name='detail_by_pk'),
    url(r'^(?P<group>[-\w]*)/(?P<kind>[-\w]*)/$', views.pet_list, name='pet_list'),
    #vistas agregadas
    url(r'^(?P<pk_or_slug>[-\w]*)/historia$', views.pet_tracing_view, name='tracing'),
]

pets/apps/users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LogoutView

from django.contrib.auth.decorators import login_required

from . import views, admin_views

from apps.users.admin import AdminFundacion
from django.contrib import admin
#admin.autodiscover()

from .admin_views import (
    OwnerProfileList,
    OwnerProfileDetail,
    OwnerProfileCreation,
    OwnerProfileUpdate,
    OwnerProfileDelete,

    PostulanteList,
    AdoptanteList,
    SeguimientoList,

    ContratoList,
    IniciarContrato,
    GenerarContrato,

    AdminIndex
)

urlpatterns = [
    
    #url(r'^$fundacion', views.CreateFundacionView.as_view(), name='createFundacion'), 
    #url(r'^blabla$', admin_views.report),
    #url(r'^fundacion-admin/$', AdminFundacion.urls),
    url(r'^$', views.SelectCreate, name='createSelect'), 
    
    url(r'^normal$', views.CreateUserView.as_view(), name='create'),
    #url(r'^fundacion$', views.CreateFundacionView, name='createFundacion'),  
    url(r'^fundacion$', views.CreateFView.as_view(), name='createFundacion'), 
    url(r'^profile/(?P<pk>[0-9]+)/$', views.ProfileDetailView.as_view(), name='user_profile'),
    url(r'^profile/$', views.UserProfileView.as_view(), name='profile'),
    url(r'^profile/edit/$', views.EditUserProfileView.as_view(), name='edit'), 
    url(r'^profile/edit_fundacion/$', views.EditFundacionProfileView.as_view(), name='edit_fundacion'),
    url(r'^login/$', views.UserLogin.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^confirm/$', views.confirm_information, name='confirm_information'),
    url(r'^recover/$', views.RecoverView.as_view(), name='recover_password'),
    url(r'^recover/reset/done/$', views.RecoverResetDoneView.as_view(), name='recover_password_done'),
    url(r'^recover/reset/(?P<token>.+)/$', views.RecoverResetView.as_view(), name='recover_password_reset'),
    url(r'^recover/(?P<signature>.+)/$', views.RecoverDoneView.as_view(), name='recover_password_sent'),

    url(r'^DoneUser$', views.UserDoneCreate, name='userdone'),
    url(r'^DoneFundacion$', views.FundacionDoneCreate, name='fundone'),

    #Urls para el crud
    url(r'^administrador/$', login_required(AdminIndex), name='f_index'),
    
     url(r'^administrador/list$', login_required(OwnerProfileList.as_view()), name='f_list'),
    url(r'^administrador/(?P<pk>\d+)$', login_required(OwnerProfileDetail.as_view()), name='f_detail'),
    url(r'^administrador/nuevo$', login_required(OwnerProfileCreation.as_view()), name='f_new'),
    url(r'^administrador/editar/(?P<pk>\d+)$', login_required(OwnerProfileUpdate.as_view()), name='f_edit'),
    url(r'^administrador/borrar/(?P<pk>\d+)$', login_required(OwnerProfileDelete.as_view()), name='f_delete'),

    url(r'^administrador/postulantes$', login_required(PostulanteList.as_view()), name='r_list'),
    url(r'^administrador/adoptantes$', login_required(AdoptanteList.as_view()), name='a_list'),
    url(r'^administrador/seguimiento$', login_required(SeguimientoList.as_view()), name='s_list'),

    url(r'^administrador/contratos/list$', login_required(ContratoList.as_view()), name='c_list'),

    url(r'^administrador/contratos/(?P<m>(\d+))/(?P<u>(\d+))/$', login_required(IniciarContrato), name='c_new'),
    url(r'^administrador/contratos/generar/(?P<r>(\d+))$', login_required(GenerarContrato), name='c_generar'),
    #url(r'^contrato/(?P<pk>\d+)$', ContratoCreation.as_view(), name='c_new'),
]

pets/pets/urls.py
from django.conf import settings
from django.conf.urls import include, url, static
from django.contrib import admin
from django.views.static import serve

#app_name = 'meupet'
#urlpatterns = [
    #url(r'^pets/', include('meupet.urls', namespace='meupet')),
#    url(r'^pets/', include(('meupet.urls', 'meupet'), namespace='meupet')),
    #path(r'^pets/', include('meupet.urls', namespace='meupet')),
#    url(r'^social/', include('social_django.urls', namespace='social')),
#    url(r'^user/', include('users.urls', namespace='users')),
#    url(r'^api/', include('api.urls', namespace='api')),
#    url(r'^admin/', include(admin.site.urls)),
#    url(r'^', include('common.urls', namespace='common')),
#
#]
admin.autodiscover()
urlpatterns = [
    url(r'^pets/', include(('apps.meupet.urls', 'meupet'), namespace='meupet')),
    url(r'^social/', include(('social_django.urls', 'social'), namespace='social')),
    url(r'^user/', include(('apps.users.urls', 'users'), namespace='users')),
    url(r'^api/', include(('api.urls', 'api'), namespace='api')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include(('apps.common.urls', 'common'), namespace='common')),
    url(r'^adopcion/', include(('apps.adopcion.urls', 'adopcion'), namespace='adopcion')),
    url(r'^gmaps/', include(('apps.gmaps.urls', 'gmaps'), namespace="gmaps")),
    
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]



if settings.DEBUG:
    urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pets/apps/users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.urls import reverse, reverse_lazy
from django.http.response import HttpResponseRedirect
from django.shortcuts import resolve_url
from django.utils.translation import ugettext as _
from django.views.generic import CreateView, TemplateView, UpdateView, DetailView
from password_reset.views import Recover, RecoverDone, Reset, ResetDone

from apps.users.forms import LoginForm, RegisterForm, UpdateUserForm, UsersPasswordRecoveryForm, UsersPasswordResetForm, RegisterFormFund, UpdateFundacionForm
from apps.users.models import OwnerProfile, Fundacion
from django.shortcuts import render

from django.shortcuts import redirect
from django.http import HttpResponse
from django.template import loader

def SelectCreate(request):
    return render(request, 'users/SelectCreate.html')

def UserDoneCreate(request):
    return render(request, 'users/doneUsuario.html')

def FundacionDoneCreate(request):
    return render(request, 'users/doneFundacion.html')

class RecoverView(Recover):
    template_name = 'users/recover.html'
    form_class = UsersPasswordRecoveryForm
    success_url_name = 'users:recover_password_sent'
    email_template_name = 'users/recover_email.txt'
    search_fields = ['username', 'email']


class RecoverDoneView(RecoverDone):
    template_name = 'users/recover.html'


class RecoverResetView(Reset):
    template_name = 'users/reset.html'
    success_url = 'users:recover_password_done'
    form_class = UsersPasswordResetForm
    token_expires = 3600 * 2


class RecoverResetDoneView(ResetDone):
    template_name = 'users/reset_done.html'


class CreateUserView(CreateView):
    model = OwnerProfile
    form_class = RegisterForm
    template_name = 'users/create.html'
    authenticated_redirect_url = reverse_lazy('meupet:index')

    msg = _('Su cuenta ha sido creada, Accede <a href="{0}">'
            'a esta pagina</a> y registra a muchos amigos :)')

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(resolve_url(self.authenticated_redirect_url))
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.is_information_confirmed = True
        return super(CreateUserView, self).form_valid(form)

    def get_success_url(self):
        """
        url = reverse('meupet:register')
        messages.success(self.request, self.msg.format(url))
        backend='django.contrib.auth.backends.ModelBackend'
        user = authenticate(
            username=self.request.POST.get('username'),
            password=self.request.POST.get('password1')
        )
        login(self.request, user, backend)
        """
        return reverse('users:userdone')
        #return render('users/doneUsuario.html')
        #return redirect('users/doneUsuario.html')

def CreateFundacionView(request):
    #log = logging.getLogger(__name__)
    if request.method == "POST":

        form = RegisterFormFund(request.POST)
        if form.is_valid():

            Fundacion = form.save()
            #log.info("ENTRO fundacion")
            #return redirect(reverse('users:create_user',kwargs={'pk': Fundacion.id}))
            return render(request, 'users/doneFundacion.html', {'form': form})
            #return render(request, 'users/create_fundacion.html', {'form': form})
        else:
            return render(request, 'users/register_fundacion.html', {'form': form})

    else:
        form = RegisterFormFund()
        return render(request, 'users/register_fundacion.html', {'form': form})

class CreateFView(CreateView):
    model = Fundacion
    form_class = RegisterFormFund
    template_name = 'users/register_fundacion.html'

    def form_valid(self, form):
        #form.instance.telefono = '1111111111'
        return super(CreateFView, self).form_valid(form)

    def get_success_url(self):
        return reverse('users:fundone')

class EditUserProfileView(LoginRequiredMixin, UpdateView):
    template_name = 'users/edit_profile.html'
    model = OwnerProfile
    form_class = UpdateUserForm

    def get_success_url(self):
        messages.success(self.request, _('Cambios guardados correctamente.'))
        return reverse('meupet:index')

    def get_object(self, queryset=None):
        return self.request.user

class EditFundacionProfileView(LoginRequiredMixin, UpdateView):
    template_name = 'users/edit_fundacion_profile.html'
    model = Fundacion
    form_class = UpdateFundacionForm

    def get_success_url(self):
        messages.success(self.request, _('Cambios guardados correctamente.'))
        return reverse('meupet:index')

    def get_object(self, queryset=None):
        return self.request.user.fundacion


class UserLogin(LoginView):
    form_class = LoginForm
    template_name = 'users/login.html'


class UserProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'users/profile.html'
    #Fundacion.objects.get(self.request.user.fundacion)
    def get_context_data(self, **kwargs):
        context = super(UserProfileView, self).get_context_data(**kwargs)
        context['object'] = self.request.user
        context['fundacion'] = self.request.user.fundacion
        context['pets'] = self.request.user.pet_set.all()
        #pets_fundacion=self.request.user.fundacion.pet_set.all()
        #context['pets_fundacion']=pets_fundacion
        return context


class ProfileDetailView(DetailView):
    template_name = 'users/profile.html'
    model = OwnerProfile

    def get_context_data(self, **kwargs):
        context = super(ProfileDetailView, self).get_context_data(**kwargs)
        context['pets'] = self.object.pet_set.all()
        #if self.request.user.is_authenticated:
        context['fundacion'] = self.object.fundacion
        return context


def confirm_information(request):
    """ This check that the user has confirmed the information and
    redirect to the correct view"""
    if request.user:
        if request.user.is_information_confirmed:
            return HttpResponseRedirect(reverse('meupet:index'))
        else:
            return HttpResponseRedirect(reverse('users:edit'))

pets/apps/users/templates/users/SelectCreate.html
{% extends '_layouts/base.html' %}
{% load i18n static %}

{% block title %}{% trans 'Crear Cuenta' %}{% endblock %}

{% block content %}
<style type="text/css">
  .btn-huge{
    padding-top:20px;
    padding-bottom:20px;
}
</style>
 <div class="row">
        <div class="col-md-5">
            <a href="{% url 'users:createFundacion'%}" class="btn btn-primary btn-lg btn-block btn-huge">Fundación</a>
        </div>
        <div class="col-md-5">
            <a href="{% url 'users:create'%}" class="btn btn-primary btn-lg btn-block btn-huge">Usuario</a>
        </div>  
  </div>
<br><br>
{% endblock content %}

pets/apps/users/templates/users/_create_fundacion.html
{% load i18n thumbnail %}

<br>
<a href="{% url 'users:createSelect'%}" class="btn btn-primary btn-lg btn-block ">Volver</a>       
<br>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}

     <div class="row">
      <div class="col-md-6">
        <div class="form-group{% if form.tipo_empresa.errors %} has-error{% endif %}">
          <label for="{{ form.tipo_empresa.id_for_label }}" class="control-label">{% trans 'Tipo' %}</label>

          <div class="controls">
            {{ form.tipo_empresa }}
            {{ form.tipo_empresa.errors }}
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div class="form-group{% if form.nombre_corto.errors %} has-error{% endif %}">
          <label for="{{ form.nombre_corto.id_for_label }}" class="control-label">{% trans 'Nombre Corto' %}</label>

          <div class="controls">
            {{ form.nombre_corto }}
            {{ form.nombre_corto.errors }}
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <div class="form-group{% if form.tipo_identificacion.errors %} has-error{% endif %}">
          <label for="{{ form.tipo_identificacion.id_for_label }}" class="control-label">{% trans 'Tipo documento' %}</label>

          <div class="controls">
            {{ form.tipo_identificacion }}
            {{ form.tipo_identificacion.errors }}
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div class="form-group{% if form.num_identificacion.errors %} has-error{% endif %}">
          <label for="{{ form.num_identificacion.id_for_label }}" class="control-label">{% trans 'Numero documento ' %}</label>

          <div class="controls">
            {{ form.num_identificacion }}
            {{ form.num_identificacion.errors }}
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <div class="form-group{% if form.email.errors %} has-error{% endif %}">
          <label for="{{ form.email.id_for_label }}" class="control-label">{% trans 'Email' %}</label>

          <div class="controls">
            {{ form.email }}
            {{ form.email.errors }}
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div class="form-group{% if form.telefono.errors %} has-error{% endif %}">
          <label for="{{ form.telefono.id_for_label }}" class="control-label">{% trans 'Telefono' %}</label>

          <div class="controls">
            {{ form.telefono }}
            {{ form.telefono.errors }}
          </div>
        </div>
      </div>
    </div>

    <div class="form-group{% if form.razon_social.errors %} has-error{% endif %}">
      <label for="{{ form.razon_social.id_for_label }}" class="control-label">{% trans 'Razón Social' %}</label>

      <div class="controls">
        {{ form.razon_social }}
        {{ form.razon_social.errors }}
      </div>
    </div>
    <!--
    <div class="form-group{% if form.username.errors %} has-error{% endif %}">
      <label for="{{ form.username.id_for_label }}" class="control-label">{% trans 'Usuario' %}</label>

      <div class="controls">
        {{ form.username }}
        <div class="help-block">{{ form.username.help_text }}</div>
        {{ form.username.errors }}
      </div>
    </div>
    -->

    <fieldset>
      <legend>{% trans 'Informacion Opcional' %}</legend>

      <div class="row">
      <div class="col-md-6">
        <div class="form-group{% if form.fecha_fundacion.errors %} has-error{% endif %}">
          <label for="{{ form.fecha_fundacion.id_for_label }}" class="control-label">{% trans 'Fecha Fundacion' %}</label>

          <div class="controls">
            {{ form.fecha_fundacion }}
            {{ form.fecha_fundacion.errors }}
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div class="form-group{% if form.logo.errors %} has-error{% endif %}">
          <label for="{{ form.logo.id_for_label }}"
                 class="control-label">{% trans 'Logo' %}</label>

          <div class="controls">
            {{ form.logo }}
            {{ form.logo.errors }}
            <span class="help-block">{{ form.profile_picture.help_text }}</span>
          </div>
        </div>
      </div>
    </div>
      
      <div class="row">
        <div class="col-md-6">
          <div class="form-group{% if form.facebook.errors %} has-error{% endif %}">
            <label for="{{ form.facebook.id_for_label }}" class="control-label">{% trans 'Facebook' %}</label>

            <div class="controls">
              {{ form.facebook }}
              <div class="help-block">{{ form.facebook.help_text|safe }}</div>
              {{ form.facebook.errors }}
            </div>
          </div>
        </div>

        <div class="col-md-6">
          <div class="form-group{% if form.twitter.errors %} has-error{% endif %}">
            <label for="{{ form.twitter.id_for_label }}" class="control-label">Twitter</label>

            <div class="controls">
              {{ form.twitter }}
              <div class="help-block">{{ form.facebook.help_text|safe }}</div>
              {{ form.twitter.errors }}
            </div>
          </div>
        </div>
      </div>
    </fieldset>

    <div class="form-group text-right">
      <input type="submit" name="submit" class="btn btn-primary" value="{% trans 'Crear Fundación' %}">
    </div>
  </form>

pets/apps/users/templates/users/doneFundacion.html
{% extends '_layouts/base.html' %}
{% load i18n static thumbnail %}

{% block title %}{% trans 'Solicitud de fundacion exitosa' %}{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-9">

       <h2>La fundación ha sido creada con exito!!</h2>

       <p ALIGN="justify">Ahora puedes registrar animales de compañía para tu fundación, primero debes crear un usuario y seleccionar la fundación a la que deseas pertenecer, puedes hacer eso desde <a href="{% url 'users:create' %}">aqui.</a></p>
       
       

      <p>Puedes compartir este sitio en las redes sociales</p>

      <ul class="list-unstyled list-inline">
        <li>
          <a href="{{ facebook_url }}" target="#" rel="noreferrer noopener">
            <img src="{% static 'img/facebook.png' %}" alt="Facebook"/>
          </a>
        </li>
        <li>|</li>
        <li>
          <a href="{{ twitter_url }}" target="_blank" rel="noreferrer noopener">
            <img src="{% static 'img/twitter.png' %}" alt="Twitter"/>
          </a>
        </li>
      </ul>

      <p>Gracias por tu apoyo! <i class="c-red fa fa-heart"></i></p>
    </div>
  </div>
{% endblock %}

pets/apps/users/templates/users/doneUsuario.html
{% extends '_layouts/base.html' %}
{% load i18n static thumbnail %}

{% block title %}{% trans 'Usuario Registrado con Exito!' %}{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-9">

      <h2>Tu cuenta ha sido creada con exito!!</h2>

       <p ALIGN="justify">Ahora puedes registrar animales de compañía para tu fundación, primero accede a tu espacio de usuario con el correo y la contraseña con la cual realizaste este registro, desde <a href="{% url 'users:login' %}">aqui.</a></p>

      <p>Puedes compartir este sitio en las redes sociales</p>

      <p>Gracias por tu apoyo! <i class="c-red fa fa-heart"></i></p>
    </div>
  </div>
{% endblock %}

pets/apps/users/templates/users/ownerprofile_confirm_delete.html
{% extends 'adminlte/base.html' %}

{% block title %}Formulario{% endblock %}
{% block content %}
	<form method="post">{% csrf_token %}
	    ¿Estás seguro que deseas borrar el curso "{{ object }}"?
	    <input type="submit" value="Borrar registro" />
	</form>
	<a class="btn btn-info" href="{% url 'users:f_list' %}">Regresar</a>
{% endblock %}

pets/apps/users/templates/users/ownerprofile_detail.html
{% extends 'adminlte/base.html' %}

{% block title %}Detalles{% endblock %}
{% block content %}
	{{ownerprofile.last_name}}
	<div class="table-responsive">
		<table class="table">
			<tr>
				<td>Identificacion: {{ownerprofile.tipo_identificacion}} - {{ownerprofile.num_identificacion}} </td>
				<th>Nombres: {{ownerprofile.nombre_completo}}</th>
			</tr>
		</table>
		<a class="btn btn-info" href="{% url 'users:f_list' %}">Regresar</a>
	</div>
{% endblock %}

pets/apps/users/templates/users/ownerprofile_list.html
{% extends 'adminlte/base.html' %}

{% block logo %}
    <div class="login-logo">
    <a href="{% block logo_href %}/{% endblock %}">
        {% block logo_text %}<b>Dale</b>La Pata{% endblock %}</a>
    </div>
{% endblock %}
{% block scripts %}

{% endblock %}
{% block content %}
    <div class="table-responsive">    
    <button><a href="{% url "users:f_new"%}">Agregar usuario</a></button>      
      <table id="myTable" class="table">
        <thead>
          <tr class="clickable-row">
            <th>Tipo Id</th>
            <th>Numero Id</th>
            <th>Nombres</th>
            <th>Email</th>
            <th>Facebook</th>
            <th>Rol</th>
            {% if object.is_superuser %}
            <th>Fundacion</th>
            {% endif %}
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          {% for ownerprofile in object_list %}
          <tr>
            <td>{{ ownerprofile.tipo_identificacion }}</td>
            <td>{{ ownerprofile.num_identificacion }}</td>
            <td>{{ ownerprofile.nombre_completo }}</td>
            <td>{{ ownerprofile.email }}</td>
            <td>{{ ownerprofile.facebook }}</td>
            <td>{{ ownerprofile.get_rol }}</td>
            {% if object.is_superuser %}
             <td>{{ ownerprofile.fundacion.nombre_corto }}</td>
            {% endif %}
            <td><a href="{% url "users:f_detail" ownerprofile.id %}">Ver</a>| 
                <a href="{% url "users:f_edit" ownerprofile.id %}">Editar</a>|
                <a href="{% url "users:f_delete" ownerprofile.id %}">Borrar</a></td>
          </tr>
          {% empty %}
            <tr>
              <td colspan="7" class="text-center bg-warning">No existen datos</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
{% endblock %}

pets/apps/users/templates/users/profile.html
{% extends '_layouts/base.html' %}
{% load i18n %}
{% load i18n static thumbnail %}

{% block title %}{{ fundacion.nombre_corto }} - {{ object.first_name }} {{ object.last_name }}{% endblock %}

{% block content %}

<div class="row">
    <div class="col-md-6">
      <h4>{% trans 'Contactar Fundacion' %}</h4>
      <ul class="list-unstyled">
        {% if fundacion.logo %}
          <li>
            <img width="20%" class="img-thumbnail" src="{{ fundacion.logo|thumbnail_url:'fundacion_thumb' }}"
                                             alt="{{ fundacion }}"/></td>
          </li>
        {% endif %}
        {% if fundacion.nombre_corto %}
          <li>
            {% trans 'Nombre' %} <i class="fa fa-name"></i>: {{ fundacion.nombre_corto }}
          </li>
        {% endif %}
        {% if fundacion.facebook %}
          <li>
            <a href="{{ fundacion.facebook }}">Facebook</a>
          </li>
        {% endif %}
        <li>
          {% trans 'Email' %} <i class="fa fa-envelope"></i>: <a href="mailto:{{ fundacion.email }}">{{ fundacion.email }}</a>
        </li>
        {% if fundacion.telefono %}
          <li>
            {% trans 'Telefono' %} <i class="fa fa-phone"></i>: {{ fundacion.telefono }}
          </li>
        {% endif %}
      </ul>

      {% if user.is_authenticated and user.id == object.id and user.is_responsable %}
        <a href="{% url 'users:edit_fundacion' %}" class="btn btn-primary">{% trans 'Modificar' %}</a>
      {% endif %}

    </div>

  
    <div class="col-md-6">
      <h4>{% trans 'Contactar Usuario que hizo el registro' %}</h4>
      <ul class="list-unstyled">
       {% if object.first_name %}
          <li>
            {% trans 'Nombre' %} <i class="fa fa-name"></i>: {{ object.nombre_completo }}
          </li>
        {% endif %}
        {% if object.facebook %}
          <li>
            <a href="{{ object.facebook }}">Facebook</a>
          </li>
        {% endif %}
        <li>
          {% trans 'Email' %} <i class="fa fa-envelope"></i>: <a href="mailto:{{ object.email }}">{{ object.email }}</a>
        </li>
        {% if object.phone %}
          <li>
            {% trans 'Telefono' %} <i class="fa fa-phone"></i>: {{ object.phone }}
          </li>
        {% endif %}
        {% if object.rol %}
          <li>
            {% trans 'Rol en fundación' %} <i class="fa fa-user"></i>: {{ object.get_rol }}
          </li>
        {% endif %}
      </ul>

      {% if user.is_authenticated and user.id == object.id %}
        <a href="{% url 'users:edit' %}" class="btn btn-primary">{% trans 'Editar' %}</a>
      {% endif %}
    </div>
 </div>

    <div class="row">
    <div class="col-md-12">
      <h4>{% trans 'Mascotas registradas' %}</h4>
      {% include '_partials/pets_list.html' %}
    </div>
  </div>
{% endblock %}

pets/apps/users/templates/users/register_fundacion.html
{% extends '_layouts/base.html' %}
{% load i18n %}

{% block title %}{% trans 'Registrar Fundacion' %}{% endblock %}

{% block content %}
  <div class="row">
    {% include 'users/_create_fundacion.html' %}
  </div>
{% endblock %}

pets/apps/users/templates/users/reset_done.html
{% extends '_layouts/base.html' %}
{% load i18n %}

{% block title %}{% trans 'Recover password' %}{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-11 col-md-offset-1">
      <p>{% trans 'Your password has been successfully changed.' %}</p>
      <p>
        {% url 'users:login' as page_url %}
        {% blocktrans %}Click <a href="{{ page_url }}">here</a> to login into your account.{% endblocktrans %}
      </p>
    </div>
  </div>
{% endblock %}