pets/api/urls.py
from django.conf.urls import url

from api import views

urlpatterns = [
    url(r'^pets/$', views.ListPets.as_view(), name='list_pets'),
    url(r'^cities/$', views.CityList.as_view(), name='city-list'),
    url(r'^states/$', views.StateList.as_view(), name='state-list'),
    url(r'^users/$', views.UserList.as_view(), name='user-list'),
]

pets/apps/adopcion/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView
from django.contrib.auth.views import LogoutView

from . import views

urlpatterns = [    
    url(r'^(?P<pk>[-\w]*)/$', views.post_new, name='create'),
    url(r'^logros$', views.logros, name='logros'),
    url(r'^tenure_create/(?P<pk>[-\w]*)/$', views.responsible_tenure, name='tenure_create'),
    url(r'^contratos/(?P<id>[-\w]*)/foto/$', views.upload_image, name='upload_image'),
    url(r'^contratos/(?P<m>(\d+))/(?P<u>(\d+))/reference/$', views.reference_add, name='reference_add'),
    #url(r'^check/(?P<e>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})$', views.checkusername, name='check'),
    url(r'^check/(?P<string>.*)$', views.checkusername, name='check'),
    url(r'^evidence/(?P<m>(\d+))/(?P<u>(\d+))/$', views.AdjuntarSeguimiento, name='user_evidence'),
    url(r'^sendnoti_evidence/(?P<relacion>(\d+))/(?P<t>(\d+))/$', views.notify_evidence, name='sendnoti_evidence'),

    #url(r'^$', views.post_new, name='create'),
]

pets/apps/meupet/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from . import views

urlpatterns = [
    # I'll keep this here for compatibility with links shared
    # on Facebook.
    url(r'^new/$', RedirectView.as_view(pattern_name='meupet:register', permanent=True)),
    url(r'^search/$', RedirectView.as_view(pattern_name='meupet:search', permanent=True)),

    url(r'^$', views.PetIndexView.as_view(), name='index'),
    url(r'^novo/$', views.RegisterPetView.as_view(), name='register'),
    url(r'^busca/$', views.SearchView.as_view(), name='search'),
    url(r'^atualizar-cadastro/(?P<request_key>\w+)/$', views.update_register, name='update_register'),
    url(r'^pet/(?P<slug>[-\w]*)/foto/$', views.upload_image, name='upload_image'),
    url(r'^(?P<slug>[-\w]*)/editar/$', views.EditPetView.as_view(), name='edit'),
    url(r'^(?P<slug>[-\w]*)/poster/$', views.poster, name='poster'),
    url(r'^(?P<slug>[-\w]*)/editar/situacao/$', views.change_status, name='change_status'),
    url(r'^(?P<slug>[-\w]*)/deletar/$', views.delete_pet, name='delete_pet'),
    url(r'^(?P<slug>[-\w]*)/registrado/$', views.registered, name='registered'),
    url(r'^(?P<pk_or_slug>[-\w]*)/$', views.pet_detail_view, name='detail'),
    url(r'^(?P<pk>[0-9]+)/$', views.pet_detail_view, name='detail_by_pk'),
    url(r'^(?P<group>[-\w]*)/(?P<kind>[-\w]*)/$', views.pet_list, name='pet_list'),
    #vistas agregadas
    url(r'^(?P<pk_or_slug>[-\w]*)/historia$', views.pet_tracing_view, name='tracing'),
]

pets/apps/users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LogoutView

from django.contrib.auth.decorators import login_required

from . import views, admin_views

from apps.users.admin import AdminFundacion
from django.contrib import admin
#admin.autodiscover()

from .admin_views import (
    OwnerProfileList,
    OwnerProfileDetail,
    OwnerProfileCreation,
    OwnerProfileUpdate,
    OwnerProfileDelete,

    PostulanteList,
    AdoptanteList,
    SeguimientoList,

    ContratoList,
    IniciarContrato,
    GenerarContrato,

    AdminIndex
)

urlpatterns = [
    
    #url(r'^$fundacion', views.CreateFundacionView.as_view(), name='createFundacion'), 
    #url(r'^blabla$', admin_views.report),
    #url(r'^fundacion-admin/$', AdminFundacion.urls),
    url(r'^$', views.SelectCreate, name='createSelect'), 
    
    url(r'^normal$', views.CreateUserView.as_view(), name='create'),
    #url(r'^fundacion$', views.CreateFundacionView, name='createFundacion'),  
    url(r'^fundacion$', views.CreateFView.as_view(), name='createFundacion'), 
    url(r'^profile/(?P<pk>[0-9]+)/$', views.ProfileDetailView.as_view(), name='user_profile'),
    url(r'^profile/$', views.UserProfileView.as_view(), name='profile'),
    url(r'^profile/edit/$', views.EditUserProfileView.as_view(), name='edit'), 
    url(r'^profile/edit_fundacion/$', views.EditFundacionProfileView.as_view(), name='edit_fundacion'),
    url(r'^login/$', views.UserLogin.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^confirm/$', views.confirm_information, name='confirm_information'),
    url(r'^recover/$', views.RecoverView.as_view(), name='recover_password'),
    url(r'^recover/reset/done/$', views.RecoverResetDoneView.as_view(), name='recover_password_done'),
    url(r'^recover/reset/(?P<token>.+)/$', views.RecoverResetView.as_view(), name='recover_password_reset'),
    url(r'^recover/(?P<signature>.+)/$', views.RecoverDoneView.as_view(), name='recover_password_sent'),

    url(r'^DoneUser$', views.UserDoneCreate, name='userdone'),
    url(r'^DoneFundacion$', views.FundacionDoneCreate, name='fundone'),

    #Urls para el crud
    url(r'^administrador/$', login_required(AdminIndex), name='f_index'),
    
     url(r'^administrador/list$', login_required(OwnerProfileList.as_view()), name='f_list'),
    url(r'^administrador/(?P<pk>\d+)$', login_required(OwnerProfileDetail.as_view()), name='f_detail'),
    url(r'^administrador/nuevo$', login_required(OwnerProfileCreation.as_view()), name='f_new'),
    url(r'^administrador/editar/(?P<pk>\d+)$', login_required(OwnerProfileUpdate.as_view()), name='f_edit'),
    url(r'^administrador/borrar/(?P<pk>\d+)$', login_required(OwnerProfileDelete.as_view()), name='f_delete'),

    url(r'^administrador/postulantes$', login_required(PostulanteList.as_view()), name='r_list'),
    url(r'^administrador/adoptantes$', login_required(AdoptanteList.as_view()), name='a_list'),
    url(r'^administrador/seguimiento$', login_required(SeguimientoList.as_view()), name='s_list'),

    url(r'^administrador/contratos/list$', login_required(ContratoList.as_view()), name='c_list'),

    url(r'^administrador/contratos/(?P<m>(\d+))/(?P<u>(\d+))/$', login_required(IniciarContrato), name='c_new'),
    url(r'^administrador/contratos/generar/(?P<r>(\d+))$', login_required(GenerarContrato), name='c_generar'),
    #url(r'^contrato/(?P<pk>\d+)$', ContratoCreation.as_view(), name='c_new'),
]

pets/pets/urls.py
from django.conf import settings
from django.conf.urls import include, url, static
from django.contrib import admin
from django.views.static import serve

#app_name = 'meupet'
#urlpatterns = [
    #url(r'^pets/', include('meupet.urls', namespace='meupet')),
#    url(r'^pets/', include(('meupet.urls', 'meupet'), namespace='meupet')),
    #path(r'^pets/', include('meupet.urls', namespace='meupet')),
#    url(r'^social/', include('social_django.urls', namespace='social')),
#    url(r'^user/', include('users.urls', namespace='users')),
#    url(r'^api/', include('api.urls', namespace='api')),
#    url(r'^admin/', include(admin.site.urls)),
#    url(r'^', include('common.urls', namespace='common')),
#
#]
admin.autodiscover()
urlpatterns = [
    url(r'^pets/', include(('apps.meupet.urls', 'meupet'), namespace='meupet')),
    url(r'^social/', include(('social_django.urls', 'social'), namespace='social')),
    url(r'^user/', include(('apps.users.urls', 'users'), namespace='users')),
    url(r'^api/', include(('api.urls', 'api'), namespace='api')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include(('apps.common.urls', 'common'), namespace='common')),
    url(r'^adopcion/', include(('apps.adopcion.urls', 'adopcion'), namespace='adopcion')),
    url(r'^gmaps/', include(('apps.gmaps.urls', 'gmaps'), namespace="gmaps")),
    
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]



if settings.DEBUG:
    urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pets/apps/meupet/models.py
import hashlib

from django.conf import settings
from django.urls import reverse
from django.db import models
from django.utils import timezone, crypto
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _

from autoslug import AutoSlugField
from django_extensions.db.models import TimeStampedModel

from apps.meupet import services
from apps.users.models import OwnerProfile, Fundacion
from apps.adopcion.models import TipoRelacion, Relacion

from django.core.validators import MaxValueValidator, MinValueValidator

     
class PetQuerySet(models.QuerySet):
    def _filter_by_kind(self, kind):
        try:
            return self.actives().filter(kind__id=int(kind)).select_related('city')
        except ValueError:
            return self.actives().filter(kind__slug=kind).select_related('city')

    def get_unpublished_pets(self):
        return self.filter(published=False)

    def get_staled_pets(self):
        """
        Pets considered as staled are not modified after a given
        number of days and don't have a request_sent date
        """
        stale_date = timezone.now() - timezone.timedelta(days=settings.DAYS_TO_STALE_REGISTER)
        return self.filter(
            modified__lt=stale_date,
            request_sent__isnull=True,
            status__in=PetStatus.objects.filter(final=False)
        )

    def actives(self):
        """
        Return only pets with active = True
        """
        return self.filter(active=True)

    def get_expired_pets(self):
        """Expired pets have request_sent date older than expected"""
        expire_date = timezone.now() - timezone.timedelta(days=settings.DAYS_TO_STALE_REGISTER)
        return self.filter(active=True, request_sent__lt=expire_date)


class KindManager(models.Manager):
    def count_pets(self, status):
        return self.filter(pet__status__in=status, pet__active=True) \
            .annotate(num_pets=models.Count('pet')).order_by('kind')


class Kind(models.Model):
    kind = models.TextField(max_length=100, unique=True)
    slug = AutoSlugField(max_length=30, populate_from='kind')

    objects = KindManager()

    def __str__(self):
        return self.kind


def get_slug(instance):
    city = ''
    if instance.city:
        city = instance.city.name
    return slugify('{}-{}'.format(instance.name, city))


class StatusGroup(models.Model):
    slug = AutoSlugField(max_length=64, unique=True, populate_from='name')
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name

class Raza(models.Model):
    nombre = models.CharField(max_length=64)
    especie = models.ForeignKey(Kind, on_delete=models.PROTECT, null=True, blank=True)

    def __str__(self):
        return self.nombre

class PetStatus(models.Model):
    group = models.ForeignKey(StatusGroup, related_name='statuses', blank=True, null=True, on_delete=models.PROTECT)
    code = models.CharField(max_length=32, unique=True)
    description = models.CharField(max_length=64)
    next_status = models.OneToOneField('self', blank=True, null=True, on_delete=models.PROTECT)
    final = models.BooleanField(default=False)

    class Meta:
        ordering = ('description',)

    def __str__(self):
        return self.description

    @property
    def next(self):
        if self.final == False:
            return self.next_status
        else :
            return self
        


class Pet(TimeStampedModel):
    MALE = 'MA'
    FEMALE = 'FE'
    PET_SEX = (
        (FEMALE, _('Hembra')),
        (MALE, _('Macho')),
    )
    SMALL = 'SM'
    MEDIUM = 'MD'
    LARGE = 'LG'
    PET_SIZE = (
        (SMALL, _('Pequeño')),
        (MEDIUM, _('Mediano')),
        (LARGE, _('Grande')),
    )
    BLANCO = '1'
    NEGRO = '2'
    AMARILLO = '3'
    CAFE = '4'
    OTRO = '5'
    COLOR = (
        (BLANCO, _('Blanco')),
        (NEGRO, _('Negro')),
        (AMARILLO, _('Dorado')),
        (CAFE, _('Cafe')),
        (OTRO, _('Otro')),
    )

    UNO = '1'
    DOS = '2'
    TRES = '3'
    CUATRO = '4'
    CINCO = '5'
    CONDICION = (
        (UNO, _('1 - Muy delgado')),
        (DOS, _('2 - Delgado')),
        (TRES, _('3 - Ideal')),
        (CUATRO, _('4 - Sobrepeso')),
        (CINCO, _('5 - Obeso')),
    )

    chip_id = models.BigIntegerField(unique=True, null=True, blank=True)
    condicion_corporal = models.CharField(max_length=1,
                            choices=CONDICION,
                            blank=True)
    peso = models.DecimalField(max_digits=5, decimal_places=2)
    color = models.CharField(max_length=250, null=True, blank=True)
    edad = models.CharField(max_length=250, null=True, blank=True)
    owner = models.ForeignKey(OwnerProfile, on_delete=models.PROTECT)
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=500)
    city = models.ForeignKey('cities.City', on_delete=models.PROTECT)
    kind = models.ForeignKey(Kind, null=True, on_delete=models.PROTECT )
    status = models.ForeignKey(PetStatus, related_name='pets', blank=True, null=True, on_delete=models.PROTECT)
    size = models.CharField(max_length=2,
                            choices=PET_SIZE,
                            blank=True)
    sex = models.CharField(max_length=2,
                           choices=PET_SEX,
                           blank=True)
    profile_picture = models.ImageField(upload_to='pet_profiles',
                                        help_text=_('Tamaño Maximo 8MB'))
    published = models.BooleanField(default=False)  # published on facebook
    request_sent = models.DateTimeField(null=True, blank=True)
    request_key = models.CharField(blank=True, max_length=40)
    active = models.BooleanField(default=True)
    slug = AutoSlugField(max_length=50, populate_from=get_slug, unique=True)
    fundacion = models.ForeignKey(Fundacion, models.DO_NOTHING, db_column='fundacion')
    raza = models.ForeignKey(Raza, models.DO_NOTHING, null=True, blank=True)

    objects = PetQuerySet.as_manager()

    def get_absolute_url(self):
        return reverse('meupet:detail', kwargs={'pk_or_slug': self.slug})

    def change_status(self):
        self.status = self.status.next
        self.save()

    def get_adoptante_actual(self):
        tipor = TipoRelacion.objects.get(nombre='Adopción')
        r = Relacion.objects.get(mascota=self , tipo_relacion = tipor)
        return r.usuario.nombre_completo()

    def is_found_or_adopted(self):
        return self.status.final

    def get_status(self):
        return self.status.description

    def get_sex(self):
        return dict(self.PET_SEX).get(self.sex)

    def get_condicion_corporal(self):
        return dict(self.CONDICION).get(self.condicion_corporal)

    def get_size(self):
        return dict(self.PET_SIZE).get(self.size)

    def request_action(self):
        hash_input = (crypto.get_random_string(5) + self.name).encode('utf-8')
        self.request_key = hashlib.sha1(hash_input).hexdigest()

        if not services.send_request_action_email(self):
            return

        self.request_sent = timezone.now()
        self.save(update_modified=False)

    def activate(self):
        self.request_sent = None
        self.request_key = ''
        self.active = True
        self.save()

    def deactivate(self):
        if not services.send_deactivate_email(self):
            return

        self.active = False
        self.save(update_modified=False)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-id']
        unique_together = ('name', 'owner')


class Photo(models.Model):
    pet = models.ForeignKey(Pet, on_delete=models.PROTECT)
    image = models.ImageField(upload_to='pet_photos')

from django.utils.timezone import now
class Achievement(models.Model):
    #REGISTER = 'RG'
    CHIPING = 'CH'
    STERILIZATION = 'ST'
    STATUS = (
        #(REGISTER, _('Registrado')),
        (CHIPING, _('Chipeado')),
        (STERILIZATION, _('Esterilizado')),
    )
    pet = models.ForeignKey(Pet, null=False, blank=False, on_delete=models.CASCADE)
    achievement = models.CharField(choices=STATUS, null=False, blank=False, max_length=2)
    creation_date = models.DateTimeField(default=now)

pets/apps/meupet/templates/meupet/edit.html
{% extends '_layouts/base.html' %}
{% load i18n %}

{% block title %}{% trans 'Editar Mascota' %}{% endblock %}

{% block content %}
  <div class="row">
    {% include 'meupet/_pet_form.html' %}
  </div>
{% endblock %}

pets/apps/meupet/templates/meupet/index.html
{% extends '_layouts/base.html' %}
{% load i18n %}

{% block title %}{% trans 'Resgistros mas recientes' %}{% endblock %}

{% block content %}
  {% include '_partials/pets_list.html' %}
{% endblock %}

pets/apps/meupet/templates/meupet/pet_detail.html
{% extends '_layouts/base.html' %}
{% load i18n static thumbnail %}

{% block metatags %}
  <link rel="canonical" href="{{ pet_url }}"/>
  <meta name="description" content="{{ pet.description }}">
  
  <meta property="og:title" content="{{ pet.name }} | {{ pet.status.description }}">
  <meta property="og:description" content="{{ pet.description }}">
  <meta property="og:url" content="{{ pet_url }}">
  <meta property="og:image"
        content="http://dalelapata.narino.gov.co{{ pet.profile_picture|thumbnail_url:'pet_thumb' }}">
  <meta property="og:site_name" content="Dale La Pata">

  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="{{ pet.name }} | Dale la Pata">
  <meta name="twitter:description" content="{{ pet.description }}">
  <meta name="twitter:image:src" content="http://www.dalelapata.narino.gov.co{{ pet.profile_picture|thumbnail_url:'pet_thumb' }}">
{% endblock %}

{% block title %}{{ pet.name }} {% if pet.status.description %} - {{ pet.status.description }} {% endif %}{% endblock %}
{% block page_title %}{{ pet.status.description }}: {{ pet.name|title }}, {{ pet.city|title }}{% endblock %}

{% block content %}
  <div class="modal fade" id="delete_pet" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">

        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title">{% trans 'Borrar mascota' %}</h4>
        </div>

        <div class="modal-body">
          <p>{% trans 'Esta seguro de eliminar la mascota?' %}</p>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'Cancelar' %}</button>

          <form action="{% url 'meupet:delete_pet' pet.slug %}" method="post" class="form-inline">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="{% trans 'Delete' %}"/>
          </form>
        </div>

      </div>
    </div>
  </div>

  <div class="row" style="background-image:url('../../static/img/fondoheader.png')">
    <div class="col-md-5">
      <a href="{{ pet.profile_picture.url }}" data-lightbox="{{ pet.slug }}" data-title="{{ pet }}">
        <img class="img-thumbnail image-pet" src="{{ pet.profile_picture|thumbnail_url:'pet_thumb' }}"
             alt="{{ pet }}"/>
      </a>
      {% if user == pet.owner %}
        <form class="form-horizontal" method="POST" enctype="multipart/form-data"
              action="{% url 'meupet:upload_image' pet.slug %}">
          {% csrf_token %}
          <input name="pet_id" value="{{ pet.id }}" type="hidden">

          <div class="form-group">
            <label for="another_picture" class="control-label">{% trans 'Agregar foto' %}</label>
            <input type="file" id="another_picture" name="another_picture">
            <span class="help-block">{% trans 'Maximo tamaño de imagen 8MB' %}</span>
          </div>
          <div class="form-group">
            <input type="submit" name="submit" class="btn btn-primary pull-right" value="{% trans 'Subir Imagen' %}">
          </div>
        </form>
      {% endif %}
    </div>

    <div class="col-md-7">
      <div class="panel panel-default" style="-webkit-border-radius: 30px;-moz-border-radius: 30px;border-radius: 30px;">
        <div class="panel-body">

          {% if pet.chip_id %}
          <div class="row" style="margin:15px">
          <div class="pet-botton col-md-4" >
          <strong >{% trans 'Numero Chip' %}:</strong>
          </div>
          <div class="col-md-8">
              {{ pet.chip_id }}
            </div>
          </div>
          {% endif %}
          <div class="row" style="margin:15px">
          <div class="pet-botton col-md-4" >
            <strong>{% trans 'Descripción' %}:</strong>
          </div>
          <div class="col-md-8">
            {{ pet.description }}
          </div>
        </div>
        <div class="row" style="margin:15px">
          <div class="pet-botton col-md-4">
            <strong>{% trans 'Ciudad' %}:</strong>
          </div>
          <div class="col-md-8">
            {{ pet.city|title }}
          </div>
        </div>

          {% if pet.size %}
          <div class="row"  style="margin:15px">
            <div class="pet-botton col-md-4">
              <strong>{% trans 'Tamaño' %}:</strong>
            </div>
            <div class="col-md-8">
              {{ pet.get_size_display }}
            </div>
          </div>
          {% endif %}

          {% if pet.sex %}
          <div class="row" style="margin:15px">
            <div class="pet-botton col-md-4">
              <strong>{% trans 'Genero' %}:</strong>
            </div>
            <div class="col-md-8">
              {{ pet.get_sex_display }}
            </div>
          </div>
          {% endif %}

          <p>
            <strong>{% trans 'Contacto' %}:</strong><br/>
            <a href="{% url 'users:user_profile' pet.owner.id %}">{{pet.owner.fundacion.nombre_corto}} - {{ pet.owner.get_full_name }}</a>
            {% if pet.owner.facebook %} | <a href="{{ pet.owner.facebook }}">Facebook</a>{% endif %}
          </p>

          <p>
            <strong>{% trans 'Compartir' %}:</strong><br/>
            <a href="http://www.facebook.com/sharer.php?u={{ pet_url }}" target="_blank" rel="noreferrer noopener">
              <img src="{% static 'img/facebook.png' %}" alt="Facebook"/>
            </a>
            <a href="http://twitter.com/share?url={{ pet_url }}" target="_blank" rel="noreferrer noopener">
              <img src="{% static 'img/twitter.png' %}" alt="Twitter"/>
            </a>
          </p>

            <div class="pull-right">
              <a href="{% url 'meupet:tracing' pet.slug %}" class="btn btn-info">{% trans 'Historia' %}</a>
              {% if not pet.status.final %}
                <!-- <form action="{% url 'meupet:change_status' pet.id %}" method="post" class="form-inline"> -->

                <form action="{%url 'adopcion:create' pet.id%}" method="GET" class="form-inline">
                  {% csrf_token %}
                  <input name="pet_id" id="pet_id" value="{{ pet.id }}" type="hidden">
                  {% if pet.status.code %}
                  <input type="submit" class="btn btn-success" value="
                            {% if pet.status.code == 'Adopción' %}
                              {% trans 'ADOPTAME!' %}
                            {% else %}
                              {% if pet.status.code == 'Extraviada' %}
                                {% trans 'NOTIFICAR AVISTAMIENTO!' %}
                              {% endif %}
                            {% endif %}"

                            {% if pet.status.final %}
                              {% trans 'disabled' %}
                            {% endif %} />

                  {% elif relacion == None %}
                    <a href="{%url 'adopcion:tenure_create' pet.id%}" class="btn btn-success">{% trans 'T. responsable' %}</a>
                  {% endif %}

                </form>


              {% if user == pet.owner %}
              <a href="{% url 'meupet:edit' pet.slug %}" class="btn btn-primary">{% trans 'Editar' %}</a>
              {% if not pet.status.final %}
                <a href="{% url 'meupet:poster' pet.slug %}" class="btn btn-primary" >{% trans 'Generar poster' %}</a>
              {% endif %}


              <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#delete_pet">
                {% trans 'ELiminar' %}
              </button>
              {% endif %}

          {% endif %}
          </div>
        </div>
      </div>
    </div>
    {% if pet.photo_set.all %}
      <div class="col-md-12">
        <h3>{% trans 'Mas fotos!' %}</h3>

        <div class="row">
          {% for photo in pet.photo_set.all %}
            <div class="col-md-3">
              <a href="{{ photo.image.url }}" data-lightbox="{{ pet.slug }}" data-title="{{ pet }}">
                <img class="img-thumbnail image-pet" src="{{ photo.image|thumbnail_url:'pet_thumb' }}"
                     alt="{{ pet }}"/>
              </a>
            </div>
            {% if forloop.counter|divisibleby:4 %}
              </div>
              <div class="row">
            {% endif %}
          {% endfor %}
          </div>
      </div>
    {% endif %}
  </div>
{% endblock %}

pets/apps/meupet/templates/meupet/pet_list.html
{% extends '_layouts/base.html' %}

{% block title %}{{ kind }} - {{ status }}{% endblock %}

{% block content %}
  {% include '_partials/pets_list.html' %}
{% endblock %}

pets/apps/meupet/templates/meupet/poster.html
{% extends '_layouts/base.html' %}
{% load i18n static thumbnail %}

{% block page %}
  <div class="container">
    <div class="row">
      <div class="col-md-12">

        <div class="text-center hidden-print">
          <a onclick="window.print()" class="btn btn-primary">{% trans 'Print' %} <i class="fa fa-print"></i></a>
        </div>

        <div class="page">
          <div class="pull-left print-logo">
            <img class="img-responsive" src="{% static 'img/logo.png' %}" alt="Logo Cadê meu Bicho">
          </div>
          <div class="pull-right print-logo">
            <img class="img-responsive" src="{% static 'img/logo.png' %}" alt="Logo Cadê meu Bicho">
          </div>

          <h1 class="text-center text-uppercase poster-headline">
            {{ pet.status.description }}
          </h1>

          <div class="text-center">
            <img class="img-responsive img-rounded img-thumbnail"
                 src="{{ pet.profile_picture|thumbnail_url:'pet_poster' }}"
                 alt="{{ pet.name }}">
          </div>

          <h2 class="text-center poster-headline">
            {{ pet.name }}
          </h2>

          {% if pet.size and pet.sex %}
            <h2 class="text-center poster-subheadline">
              {% trans 'Size' %} {{ pet.get_size_display|lower }}, {{ pet.get_sex_display|lower }}
            </h2>
          {% endif %}

          <p class="font-1_8rem">{{ pet.description }}</p>

          <h3>{% trans 'Contact' %}</h3>

          <ul class="list-unstyled font-1_8rem">
            <li>
              {% trans 'Email' %} <i class="fa fa-envelope"></i>: {{ pet.owner.email }}
            </li>
            {% if pet.owner.phone %}
              <li>
                {% trans 'Phone' %} <i class="fa fa-phone"></i>: {{ pet.owner.phone }}
              </li>
            {% endif %}
          </ul>

          <div class="pull-right">
            <p class="font-1_8rem">{% trans 'Visit:' %} www.dalelapata.com</p>
          </div>
        </div>

      </div>
    </div>
  </div>
{% endblock %}